modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/ultimate-car-mod/issues"
[[mods]]
modId = "car"
version = "${mod_version}"
displayName = "Ultimate Car Mod"
updateJSONURL = "https://update.maxhenkel.de/neoforge/car"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ultimate-car-mod"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''This mod brings cars, road construction and biodiesel production into your Minecraft world'''
[[dependencies.car]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.car]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,1.21.1]"
ordering = "NONE"
side = "BOTH"
[[dependencies.car]]
modId = "jei"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.car]]
modId = "theoneprobe"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"
[[dependencies.car]]
modId = "jade"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "BOTH"